name: Safe: Sync Upstream -> main -> ameego-custom

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  sync-and-merge:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo (full history)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure git user
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Add upstream remote and fetch
        run: |
          git remote add upstream https://github.com/gitroomhq/postiz-app.git || true
          git fetch upstream --prune

      - name: Checkout main
        run: git checkout main

      - name: Merge upstream/main into main
        run: |
          git merge --ff-only upstream/main || git merge upstream/main --no-edit || true

      - name: Push main to origin (if changed)
        run: git push origin main || echo "No changes to push for main"

      - name: Ensure ameego-custom exists
        run: |
          git fetch origin
          if git show-ref --verify --quiet refs/heads/ameego-custom; then
            git checkout ameego-custom
          else
            if git ls-remote --exit-code --heads origin ameego-custom; then
              git checkout -b ameego-custom origin/ameego-custom
            else
              git checkout -b ameego-custom
            fi
          fi

      - name: Try merge main into ameego-custom
        id: merge_attempt
        run: |
          set -e
          if git merge main --no-edit; then
            echo "merge_status=success" >> $GITHUB_OUTPUT
          else
            echo "merge_status=conflict" >> $GITHUB_OUTPUT
          fi

      - name: Push ameego-custom when merge succeeded
        if: steps.merge_attempt.outputs.merge_status == 'success'
        run: git push origin ameego-custom

      - name: Create PR if merge failed (conflicts)
        if: steps.merge_attempt.outputs.merge_status == 'conflict'
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "chore: auto-sync main -> ameego-custom (conflicts)"
          title: "Sync: Merge main → ameego-custom (please resolve conflicts)"
          body: |
            Automatic merge of `main` into `ameego-custom` failed due to conflicts.
            Please review and resolve conflicts in this PR.
          base: ameego-custom
          head: main
