name: Safe: Sync Upstream -> main

on:
  workflow_dispatch:
  schedule:
    - cron: "0 6 * * *"  # daily at 06:00 UTC (optional)

permissions:
  contents: write  # needed to push branches & create PRs

jobs:
  sync-upstream-into-main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo (full history)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure git user
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Add upstream and fetch
        run: |
          # Safe upstream definition — change only if upstream repo is different
          git remote add upstream https://github.com/gitroomhq/postiz-app.git || true
          git fetch upstream --prune

      - name: Ensure main branch
        run: |
          git checkout main

      - name: Merge upstream/main into main (safe merge)
        run: |
          # prefer fast-forward, otherwise do a normal merge without editing commit message
          git merge --ff-only upstream/main || git merge upstream/main --no-edit || true

      - name: Push updated main (if changed)
        run: |
          git push origin main || echo "No changes to push for main"

      - name: Prepare custom branch ameego-custom
        run: |
          git fetch origin
          if git show-ref --verify --quiet refs/heads/ameego-custom; then
            git checkout ameego-custom
          else
            # try to create from remote if exists, else create new branch locally
            if git ls-remote --exit-code --heads origin ameego-custom; then
              git checkout -b ameego-custom origin/ameego-custom
            else
              git checkout -b ameego-custom
            fi
          fi

      - name: Try to merge main into ameego-custom
        id: merge_attempt
        run: |
          set -e
          if git merge main --no-edit; then
            echo "merge_status=success" >> $GITHUB_OUTPUT
          else
            echo "merge_status=conflict" >> $GITHUB_OUTPUT
            # create marker file to indicate conflict
            echo "CONFLICT" > merge_conflict_marker.txt
          fi

      - name: Push ameego-custom when merge succeeded
        if: steps.merge_attempt.outputs.merge_status == 'success'
        run: git push origin ameego-custom

      - name: Create PR if merge failed (conflicts)
        if: steps.merge_attempt.outputs.merge_status == 'conflict'
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "chore: auto-sync main -> ameego-custom (conflicts)"
          title: "Sync: Merge main → ameego-custom (please resolve conflicts)"
          body: |
            Automatic merge of `main` into `ameego-custom` failed due to conflicts.
            This PR contains upstream changes that need manual resolution.
          base: ameego-custom
          head: main
